Geração de recibos
IBAD-Ibirama/ibad pull request #15
Opened 2020-09-19 20:17 UTC by MarioFronza

### Descrição 
Funcionalidade para gerar recibos de movimentações. O usuário pode selecionar uma movimentação que deseja gerar um recibo de pagamento através do botão **Gerar recibo**. Uma nova aba será aberta contendo o recibo em PDF.

### Demonstração
<img src="https://cdn.discordapp.com/attachments/737806209662451835/756971966459805746/ezgif.com-video-to-gif.gif" />

2020-09-19 20:57 UTC, jpedroschmitz approved these changes, later dismissed
Sensacional, bom trabalho @MarioFronza!

2020-09-19 21:35 UTC, lucasfusinato requested changes
Ficou bem legal a funcionalidade!

Necessário apenas verificar duas situações no arquivo **receipt.blade.php**, onde acrescentei um comentário.

2020-09-19 21:35 UTC, lucasfusinato commented on resources/views/receipt.blade.php
> +            <p>UDESC - Alto Vale - CEAVI</p>
Para a versão final do sistema, verificar se aqui devem ser informados os dados do IBAD, e não da UDESC.

2020-09-19 21:35 UTC, lucasfusinato commented on resources/views/receipt.blade.php
> +            <p>Recebi de {{$move->user->name}} a importância de cinquenta reais</p>
Verificar aqui que a descrição **cinquenta** está fixada no código-fonte ao invés de ser apresentada de acordo com o valor informado

A biblioteca [wgenial/numeroporextenso-php](https://github.com/wgenial/numeroporextenso-php) poderia ser utilizada neste caso.

2020-09-20 14:47 UTC, lucasfusinato approved these changes

2020-09-20 17:59 UTC, jpedroschmitz approved these changes

2020-09-20 17:59 UTC, merged