feat: cadastro de responsáveis
IBAD-Ibirama/ibad pull request #16
Opened 2020-09-19 20:58 UTC by jpedroschmitz

**Descrição** 

Funcionalidade para cadastro de responsáveis.

2020-09-19 23:19 UTC, GustavoSantosCS requested changes

2020-09-19 23:19 UTC, GustavoSantosCS commented on database/factories/ResponsibleFactory.php
> +});
Apenas um comentário
Essa classe não acrescenta nada no projeto! Não há razões para mantê-la.

2020-09-19 23:19 UTC, GustavoSantosCS commented on database/seeds/ResponsibleSeeder.php
> +}
Apenas um comentário
Essa classe não acrescenta nada no projeto! Não há razões para mantê-la.

2020-09-19 23:19 UTC, GustavoSantosCS commented on resources/views/layouts/app.blade.php
> +  <script>
O script a baixo tem impacto em toda a aplicação?
Se não ele deve ser movido para a pagina onde ele será utilizado!

Vcs podem criar um arquivo aparte e so "instanciar" ele nos locais onde ele é requerido

2020-09-19 23:19 UTC, GustavoSantosCS commented on resources/views/responsibles/create.blade.php
> +
Código duplicado:
resources/views/responsibles/create.blade.php 
resources/views/responsibles/edit.blade.php

Ele pode fazer parte de uma arquivo aparte!
e ser declarado na @section('script')

2020-09-19 23:19 UTC, GustavoSantosCS commented on resources/views/responsibles/edit.blade.php
> +</script>
Código duplicado:
resources/views/responsibles/create.blade.php 
resources/views/responsibles/edit.blade.php

Ele pode fazer parte de uma arquivo aparte!

2020-09-19 23:19 UTC, GustavoSantosCS commented on resources/views/layouts/app.blade.php
>    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigi
declaração de arquivos js deve vir no final do arquivo, antes do fechamento da tag body!

2020-09-19 23:19 UTC, GustavoSantosCS commented on resources/views/responsibles/create.blade.php
> +<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" defer></script>
essa linha já esta declarada no Template, sua redeclararão não é necessária aqui

2020-09-19 23:19 UTC, GustavoSantosCS commented on resources/views/responsibles/edit.blade.php
> +<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" defer></script>
essa linha já esta declarada no Template, sua redeclararão não é necessária aqui

2020-09-19 23:23 UTC, GustavoSantosCS approved these changes, later dismissed
Eu aprovo o merge já que não há realmente algo errado!
Entretanto sugiro eliminar a duplicidade com um arquivo aparte! E a remoção do codigo js no Template.

2020-09-20 18:55 UTC, lucasfusinato requested changes
Em geral está tudo certo!

Necessário apenas revisar as alterações realizadas no layout padrão **app.blade.php** conforme os comentários acrescentados neste arquivo, pois estas impactam em todo o projeto.

2020-09-20 18:55 UTC, lucasfusinato commented on database/seeds/ResponsibleSeeder.php
> +}
Conforme revisão do @GustavoSantosCS, esse arquivo poderia ser removido.

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/layouts/app.blade.php
> +  <script>
Conforme revisão do @GustavoSantosCS, estes scripts são específicos para o cadastro de responsáveis, portanto não deveriam estar em um arquivo global.

Minha sugestão para esse caso é a seguinte:

1. Criar um arquivo **responsibles.js** no caminho **public/js/pages/**
2. Declarar este código dentro do novo arquivo criado
3. Adicionar nos arquivos **create.blade.php** e **edit.blade.php** o seguinte trecho de código dentro da seção de scripts: `<script src="{{ asset('public/js/pages/responsibles.js') }}"></script>`

Desta forma o código poderá ser reutilizado apenas nos momentos em que for realmente necessário.

2020-09-20 18:55 UTC, lucasfusinato commented on database/factories/ResponsibleFactory.php
> +});
Conforme revisão do @GustavoSantosCS, este arquivo poderia ser removido já que não possui conteúdo.

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/layouts/app.blade.php
> +    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" defer></script>
Acredito que essas duas tags de script tenham sido adicionadas no topo do arquivo devido a algum problema na ordem de carregamento (necessário verificar). Nesse caso, foi aberta a issue #17 que poderia corrigir a situação.

Por ora, recomendo que estes arquivos sejam mantidos no final do arquivo.

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/responsibles/create.blade.php
> +                <option value="{{$athlete->id}}" id="{{$athlete->user->name}}" onclick="adicionarNovoAtleta(this.value,this.id)">{{$athlete->user->name}}</option>
Verificar se o **id** desse elemento realmente deve ser o nome do atleta.

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/responsibles/create.blade.php
> +<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" defer></script>
Conforme revisão do @GustavoSantosCS, verificar que esse script já é declarado no layout base.

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/responsibles/edit.blade.php
> +                <option value="{{$athlete->id}}" id="{{$athlete->user->name}}" onclick="adicionarNovoAtleta(this.value,this.id)">{{$athlete->user->name}}</option>
Verificar se o **id** desse elemento realmente deve ser o nome do atleta.

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/responsibles/edit.blade.php
> +<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" defer></script>
Conforme revisão do @GustavoSantosCS, verificar que esse script já é declarado no layout base.

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/responsibles/edit.blade.php
> +  });
Verificar que atualmente este trecho de código também está sendo declarado no layout base,

2020-09-20 18:55 UTC, lucasfusinato commented on resources/views/responsibles/create.blade.php
> +  });
Verificar que atualmente este trecho de código também está sendo declarado no layout base,

2020-09-22 12:53 UTC, jpedroschmitz commented on resources/views/responsibles/create.blade.php
> +<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" defer></script>
Em nennhum local do layout esse script é importado. Ele é apenas um script de máscara para jQuery

2020-09-22 15:13 UTC, lucasfusinato approved these changes

2020-09-22 16:52 UTC, MarioFronza approved these changes

2020-09-22 17:46 UTC, merged