Grupo 2/base
IBAD-Ibirama/ibad pull request #26
Opened 2020-09-22 15:09 UTC by GustavoSantosCS

Essa são as funções que essa PR adiciona:
Manter Treinos
Manter Faltas
Manter Limite de Faltas

2020-09-22 15:23 UTC, lucasfusinato requested changes
Bom trabalho!

Necessário verificar situação que está gerando problema no **composer.json**.

2020-09-22 15:23 UTC, lucasfusinato commented on public/css/styles.css
> +.hide{
Esse seletor já não é declarado pelo bootstrap?

2020-09-22 15:23 UTC, lucasfusinato commented on composer.json
> +        "tplaner/when": "^3.0"
Verificar que está faltando uma vírgula aqui, e deste modo não é possível executar o comando `composer install`.

2020-09-22 15:23 UTC, lucasfusinato commented on .env.example
> +DB_CONNECTION=pgsql
Apenas uma observação: acredito que não seja necessário alterar esse arquivo, mas entendo que deve ter sido alterado para facilitar o início do projeto ao realizar o `git clone`.

2020-09-22 15:59 UTC, GustavoSantosCS commented on composer.json
> +        "tplaner/when": "^3.0"
Aconteceu durante o merge com a master! Foi mau!

2020-09-22 16:16 UTC, MarioFronza submitted a review, later dismissed
Bom trabalho @GustavoSantosCS !

2020-09-22 21:32 UTC, lucasfusinato approved these changes, later dismissed

2020-09-22 23:29 UTC, jpedroschmitz requested changes
PR bem grande, deixei alguns comentários em relação a páginas com muito código, creio que o `js` poderia ir para arquivos separados. Além disso, seria legal corrigir os erros de ortografia, os que encontrei eu fui marcando.

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/frequency/edit.blade.php
> +      console.log(athlete)
Faltou remover esse `console.log`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/frequency/create.blade.php
> +                    console.log(respose);
Faltou remover esse `console.log`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/frequency/create.blade.php
> +      console.log(athlete)
Faltou remover esse `console.log`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/edit.blade.php
> +</script>
Acho que esse código JS aqui de quase 100 linhas poderia ir para um arquivo próprio dentro de `public/js/pages/<nome_da_funcionalidade>`. Aí aqui só fica o import.

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/create.blade.php
> +</script>
Esse código JS aqui de 100 linhas poderia ir para um arquivo próprio dentro de `public/js/pages/<nome_da_funcionalidade>`. Aí aqui só fica o import.

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/show.blade.php
> +                    <h3><b>Turma - {{ $training->team ? $training->team->name : 'Turma Não Encotrada' }}</b></h3>
`Encontrada`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/edit.blade.php
> +            return ['Sabado', 'sa']
`Sábado`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/create.blade.php
> +        auxiliaryTitle.textContent = "Essa turma não necessita de ter ajudantes!";
`Essa turma não necessita ajudantes`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/create.blade.php
> +                                        <label for="day_select">Numero de Treinos Que Serão Cadastrados:</label>
`Número`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/create.blade.php
> +                                        <label for="training_repeat">Data do final do periodo:</label>
`Data final do período`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/create.blade.php
> +                                        <label for="training_init">Data do inicio do periodo:</label>
`Data de início do período`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/create.blade.php
> +                            <label id="titleAuxiliary" class="mt-4 mb-2">Periodo de Repetição</label>
`Período`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/frequency/index.blade.php
> +                                {{$fault->faltas >= $faultLimit->limit ? 'Atleta não esta de acordo com a presença' :''}}
`está`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/frequency/index.blade.php
> +                            <label id="titleAuxiliary">Periodo</label>
`Período`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/frequency/edit.blade.php
> +                        alert('Não foi possivel realizar a chamada');
`possível`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/faultlimit/create.blade.php
> +                                Esse limite de faltas passara a valer a partir de {{date("d-m-Y \a\s H:i")}}
`passará`

2020-09-22 23:29 UTC, jpedroschmitz commented on app/Http/Controllers/TrainingController.php
> +        session()->flash('warning', "Não foi possivel remover o Treino.");
`Possível`

2020-09-22 23:29 UTC, jpedroschmitz commented on app/Http/Controllers/TrainingController.php
> +        session()->flash('failure', "Não é possivel remover o treino com frequencia.");
`frequência`

2020-09-22 23:29 UTC, jpedroschmitz commented on app/Http/Controllers/TrainingController.php
> +        'training_end_time' => 'a hora de termino do treino',
`início` e `término`

2020-09-22 23:29 UTC, jpedroschmitz commented on app/Http/Controllers/TrainingController.php
> +        session()->flash('failure', "Não é possivel alterar dado do treino com frequencia.");
`Não é possível alterar dados de um treino com frequência.`

2020-09-22 23:29 UTC, jpedroschmitz commented on app/Http/Controllers/TrainingController.php
> +        'training_repeat' => 'o dia de fim do periodo',
`início`, `término` e `período`

2020-09-22 23:29 UTC, jpedroschmitz commented on app/Http/Controllers/FrequencyController.php
> +            session()->flash('warning', "Não foi possivel ediatar a chamada");
`Não foi possível editar`

2020-09-22 23:29 UTC, jpedroschmitz commented on app/Http/Controllers/FrequencyController.php
> +            session()->flash('warning', "Não foi possivel cadastrar a chamada");
`Não foi possível`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/frequency/index.blade.php
> +                                    Numero de Faltas: {{$fault->faltas }}
`Número`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/layouts/app.blade.php
> +                                href="{{ route('frequency.index') }}">Frequencias</a>
`Frequências`

2020-09-22 23:29 UTC, jpedroschmitz commented on resources/views/training/edit.blade.php
> +        auxiliaryTitle.textContent = "Essa turma não necessita de ter ajudantes!";
`Essa turma não necessita ajudantes`

2020-09-23 00:29 UTC, lucasfusinato commented on resources/views/frequency/edit.blade.php
> +      console.log(athlete)
Apenas uma observação:

Nesse caso, o `const [athlete] = athletes.filter(athlete => athlete.id == id);`

Poderia ser substituído por `const athlete = athletes.find(athlete => athlete.id == id);`

2020-09-27 21:21 UTC, GustavoJung commented on resources/views/training/edit.blade.php
> +</script>
Feito, separei o código e deixei o import pro arquivo dele.

2020-09-27 21:21 UTC, GustavoJung commented on resources/views/training/create.blade.php
> +</script>
Feito, separei o código e deixei o import pro arquivo dele.

2020-09-28 16:28 UTC, MarioFronza approved these changes

2020-09-28 16:53 UTC, jpedroschmitz approved these changes

2020-09-28 18:02 UTC, merged