chore: padrao laravel/ui para arquivos frontend
IBAD-Ibirama/ibad pull request #37
Opened 2020-10-03 20:33 UTC by lucasfusinato

Altera a importação de dependências externas do frontend, utilizando o padrão especificado na [documentação do Laravel](https://laravel.com/docs/7.x/frontend), de modo que as dependências sejam compiladas um um único arquivo JS e um único arquivo CSS.

2020-10-04 14:29 UTC, jpedroschmitz requested changes
PR muito importante, bom trabalho @lucasfusinato!

Deixei alguns comentário de mudanças que talvez sejam necessárias para que a aplicação carregue mais rapidamente, removendo algumas bibliotecas e trocando as fontes.

2020-10-04 14:29 UTC, jpedroschmitz commented on resources/sass/app.scss
> +@import url('https://fonts.googleapis.com/css?family=Nunito');
Como mencionei no outro comentário, se vamos trocar a fonte, podemos remover esse import.

2020-10-04 14:29 UTC, jpedroschmitz commented on resources/sass/_variables.scss
> +$font-family-sans-serif: 'Nunito', sans-serif;
Essa fonte vem padrão com o Laravel, para o projeto inicial. Podemos remover em favor da padrão do sistema, dado que isso resultará em loads mais rápidos da aplicação.

```css
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
```

2020-10-04 14:29 UTC, jpedroschmitz commented on resources/js/bootstrap.js
> +window._ = require('lodash');
Não usamos lodash, podemos remover (tirar das dependências também)

2020-10-04 14:29 UTC, jpedroschmitz commented on resources/js/bootstrap.js
> +    window.Popper = require('popper.js').default;
Não usamos o Popper.js, podemos remover (das dependências também)

2020-10-04 14:29 UTC, jpedroschmitz commented on resources/js/bootstrap.js
> +window.axios = require('axios');
Não usamos o Axios, podemos remover (das dependências também)

2020-10-04 15:17 UTC, lucasfusinato commented on resources/js/bootstrap.js
> +window.axios = require('axios');
Removido no commit 19c60bf

2020-10-04 15:18 UTC, lucasfusinato commented on resources/js/bootstrap.js
> +    window.Popper = require('popper.js').default;
O Popper foi mantido pois é necessário para o funcionamento de alguns componentes do Bootstrap, conforme [documentação](https://getbootstrap.com/docs/4.0/getting-started/introduction/)

2020-10-04 15:18 UTC, lucasfusinato commented on resources/sass/_variables.scss
> +$font-family-sans-serif: 'Nunito', sans-serif;
Alterado no commit 19c60bf

2020-10-04 15:18 UTC, lucasfusinato commented on resources/sass/app.scss
> +@import url('https://fonts.googleapis.com/css?family=Nunito');
Removido no commit 19c60bf

2020-10-04 15:20 UTC, lucasfusinato commented on resources/js/bootstrap.js
> +window._ = require('lodash');
Removido no commit 19c60bf

2020-10-04 15:28 UTC, jpedroschmitz approved these changes
Perfeito, mandou muito!

2020-10-06 17:02 UTC, GustavoSantosCS approved these changes

2020-10-06 18:36 UTC, merged