feat: User CRUD and auth
IBAD-Ibirama/ibad pull request #5
Opened 2020-08-09 19:35 UTC by jpedroschmitz

This PR will create user CRUD and auth, with permissions.

At this point, the following functionalities are working:

- [x] register user;
- [x] login (with the remember me flag);
- [x] forgot password;
- [x] permissions to access pages;

What we need to do:

- [ ] basic app layout, following some bootstrap theme or template;
- [ ] create, edit, delete and list users;
- [ ] translate pages to Portuguese;

2020-08-12 22:52 UTC, jpedroschmitz commented on database/migrations/2020_08_11_013007_create_system_users_table.php
> +        });
Precisamos mesmo de outra migration para o usuário? Já havia sido criada uma com as permissões e também para o usuário

2020-08-12 22:52 UTC, jpedroschmitz commented on routes/web.php
> +Route::resource('systemUser','SystemUserController');
Essas rotas são protegidas, então elas precisam ir depois de `Auth::routes()`

2020-08-12 22:52 UTC, jpedroschmitz commented on routes/web.php
>  });
Essa rota pode ser removida

2020-08-12 22:52 UTC, jpedroschmitz commented on app/SystemUser.php
> +}
Conforme comentei antes, acho que ñ precisamos do `SystemUser`, já que temos um usuário.

2020-08-21 22:57 UTC, lucasfusinato submitted a review, later dismissed

2020-08-21 23:15 UTC, MarioFronza submitted a review, later dismissed

2020-08-22 16:46 UTC, JefiPNZ requested changes
Outras observações:
 - Acredito que seja melhor ao invés de chamar o PermissionSeeder diretamente, adicionar o PermissionSeeder dentro do DatabaseSeeder, com o objetivo de que todo o banco seja populado, inclusive dados que sejam de outros módulos, quando chamado o php artisan migrate:refresh --seed e caso alguém queira um seeder específico, chame este diretamente.
- Quando feito login com o admin@admin.com não foi possível acessar o login de Usuário. devido a ausência de uma role (provavelmente devido a em alguns lugares a role admin estar maiusculo) e gerou erro em tela (ou 500 quando testado em produção).
- Estas informações de login e seeding poderiam estar em algum lugar (ex: no readme ou no notion) para garantir que todos estejam cientes de como realizar o seed e login, ou caso sejam alteradas as informações.
- Se for necessário chamar o middleware em todos os controllers (para evitar estourar erro) seria util ter isto no controller base (teria que ver se o laravel fornece uma forma nativa de injetar este comportamento ou se pode ser alterada a classe "Controller")

2020-08-22 16:46 UTC, JefiPNZ commented on app/Http/Controllers/UserController.php
> +    public function index()
Não foi adicionado o Middleware no construtor. Neste caso se for acessado diretamente o link ocorrerá erro 500 devido a ausência de um Usuário logado.
```suggestion
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
```

2020-08-22 16:46 UTC, JefiPNZ commented on database/seeds/PermissionsSeeder.php
> +        $adminRole = Role::create(['name' => 'Admin']);
Aqui o nome da role foi denominado Admin ("A" maiusculo), porém ao longo do sistema está sendo chamado admin ("a" minusculo) isto está certo?

2020-08-22 16:46 UTC, JefiPNZ commented on database/seeds/PermissionsSeeder.php
> +        $user->assignRole($adminRole);
Usuário "normal" está com role de admin.

2020-09-09 22:56 UTC, ipdmartins commented
Essa pull request trata das implementações feitas até agora. Como segue:
- Crud de usuários;
- Crud de atletas;
- Crud de movimentações financeiras;
- Geração de relatório financeiro;
- Crud de patrocinadores;
- Permissões de usuários: admin, financeiro, atleta, treinador e responsável;

2020-09-09 23:11 UTC, ipdmartins commented
Essa pull request trata das implementações feitas até agora. Como segue:

Crud de usuários;
Crud de atletas;
Crud de movimentações financeiras;
Geração de relatório financeiro;
Crud de patrocinadores;
Permissões de usuários: admin, financeiro, atleta, treinador e responsável;

2020-09-10 23:03 UTC, JefiPNZ approved these changes

2020-09-10 23:53 UTC, lucasfusinato approved these changes
Aprovo as alterações com o objetivo de dar fluxo ao trabalho, de forma que os outros módulos já possam iniciar a integração das funcionalidades no projeto principal.

Destaquei na revisão algumas correções que precisariam ser revistas em rotinas específicas antes do término do trabalho.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Athlete.php
> +    protected $fillable = [
Por uma questão de boas práticas, os atributos da classe poderiam ser declarados antes de qualquer método. Mas é apenas uma questão de organização.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Http/Controllers/AthleteController.php
> +        $athlete->blood_type = str_replace(' ', '', $athlete->blood_type);
Qual a necessidade desse tratamento? Não seria melhor tratar as informações durante o cadastro, para que esteja corretas no banco de dados?

2020-09-10 23:53 UTC, lucasfusinato commented on app/Http/Controllers/AthleteController.php
> +        $athlete->update([
Verifiquei que o mesmo processamento está repetido na inclusão e na alteração. Penso que seria interessante abstrair isso em um único ponto do código, facilitando a manutenção posteriormente. Em ambos os casos poderia ser usado o método **save**, pois o _framework_ identifica se deve incluir ou alterar de acordo com o **id** do objeto.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Http/Controllers/MovesController.php
> +        // $moves = Moves::whereDate('data', '2020-09-06');
Verificar se esse comentário será importante como lembrete para alguma alteração futura nesse método. Caso contrário, poderia ser removido pois não agrega no código.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Http/Controllers/MovesController.php
> +        $moves->update([
Seria interessante a reutilização deste método com o método de inserção, evitando código duplicado.

2020-09-10 23:53 UTC, lucasfusinato commented on app/User.php
> +    public function hobbies(){
Por questão de organização e boas práticas, penso que seria interessante apresentar primeiro os atributos da classe, e só depois os métodos.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Sponsor.php
> +    protected $dates = [
Esses valores para as datas já não são definidos na classe por padrão?

2020-09-10 23:53 UTC, lucasfusinato commented on app/Providers/AuthServiceProvider.php
> +            return $user->hasRole('admin') ? true : null;
Esse método **hasRole** não retorna um valor booleano? Nesse caso não seria necessário o if ternário, bastaria dar um **return $user->hasRole('admin')**.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Moves.php
> +class Moves extends Model
Conforme padrões do _Laravel_, também especificados no padrão de desenvolvimento que definimos para o projeto, os nomes das classes de modelo devem estar escritos no singular. Nesse caso seria **Move**.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Http/Controllers/MovesReportController.php
> +        foreach ($moves as &$move) {
Nesse caso não é preciso passar a variável **$move** por referência com o operador **&**. Primeiro porque é um objeto, e os atributos dos objetos são sempre atualizados, independente de ser passado por referência ou não. E segundo, nesse caso, que não há nenhuma atribuição de valor para essa variável ou para seus atributos.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Http/Controllers/SponsorController.php
> +            'cnpj' => 'required',
Verificar que, diferentemente da inclusão, na alteração do registro está permitindo cadastrar dois patrocinadores com o mesmo CNPJ. Acredito que essa validação não foi aplicada na alteração pois o registro alterado estaria duplicado com o CNPJ dele mesmo. Nesse [artigo](https://www.csrhymes.com/2019/06/22/using-the-unique-validation-rule-in-laravel-form-request.html) é mostrada uma solução para esse caso.

2020-09-10 23:53 UTC, lucasfusinato commented on database/factories/AthleteFactory.php
> +        //
Como esse arquivo não tem nenhum conteúdo, sendo apenas o padrão gerado pelo _framework_, acredito que não há necessidade de mantê-lo no projeto.

2020-09-10 23:53 UTC, lucasfusinato commented on resources/views/pdf.blade.php
> +            <th>Descricao</th>
Corrigir ortografia.

2020-09-10 23:53 UTC, lucasfusinato commented on app/Http/Controllers/MovesController.php
> +class MovesController extends Controller
Conforme destacado também no modelo, a convenção no Laravel e também nos padrões de desenvolvimento definidos para o trabalho seria que os o nome do controller também esteja escrito no singular, sendo nesse caso **MoveController**.

2020-09-10 23:53 UTC, lucasfusinato commented on resources/views/moves/create.blade.php
> +              <input type="text" class="form-control{{$errors->has('value') ? ' border-danger' : '' }}" id="value" name="value" value="">
Uma dúvida: esse valor não deveria ser um número/float?

2020-09-10 23:53 UTC, lucasfusinato commented on database/migrations/2020_08_18_235117_create_moves_table.php
> +            $table->string("value");
Uma dúvida: esse valor não deveria ser um número/float?

2020-09-10 23:53 UTC, lucasfusinato commented on resources/views/pdf.blade.php
> +            <span>R${{$totalDeposit}},00</span>
Verificar conforme comentários no modelo, que parece que esse valor deveria ser armazenado como um número/float. Nesse caso vi que o controlador faz os tratamentos antes de emitir o relatório para converter o valor em float. Porém, se eu tiver duas entradas cadastradas, uma com o valor **2.50**, que representa **R$2,50**, e outra com o valor **1.20**, que representa **R$1,20**, o valor da variável $totalDeposit será **3.70**, que representa **R$3,70**, mas nesse caso seria renderizado no relatório como **R$3.70,00**.

2020-09-10 23:53 UTC, lucasfusinato commented on tests/Builders/SponsorBuilder.php
> +    public function create($Quantity = null)
Não sei se é algo gerado automaticamente pelos testes, mas de acordo com as convenções que estamos utilizando no projeto, a variável **$Quantity** deveria estar escrita em **lowerCamelCase**, nesse caso seria **$quantity**.

2020-09-10 23:53 UTC, lucasfusinato commented on tests/Builders/UserBuilder.php
> +    public function create($Quantity = null)
Conforme destacado no outro arquivo:

> Não sei se é algo gerado automaticamente pelos testes, mas de acordo com as convenções que estamos utilizando no projeto, a variável **$Quantity** deveria estar escrita em **lowerCamelCase**, nesse caso seria **$quantity**.

2020-09-10 23:53 UTC, lucasfusinato commented on tests/Feature/SponsorTest.php
> +        //     ]);
Verificar necessidade de manter esse código comentado.

2020-09-10 23:53 UTC, lucasfusinato commented on tests/Feature/SponsorTest.php
> +        //     ]);
Verificar necessidade de manter esse código comentado.

2020-09-10 23:53 UTC, lucasfusinato commented on tests/TestCase.php
> +    public function sponsor(): SponsorBuilder
Aqui eu tenho uma dúvida se esse é um padrão para os testes no Laravel ou algo do tipo, mas realmente os métodos **sponsor** e **user** deveriam estar na classe base de testes?

2020-09-11 00:31 UTC, GustavoSantosCS commented
ok

2020-09-11 00:36 UTC, GustavoSantosCS approved these changes

2020-09-11 00:40 UTC, GustavoSantosCS commented
Nosso modulo requer uma associação entre  Team com Athlete! Essa associação é um OneToMay. Quando a gente fizer a integração a gente coloca isso! Tanto a migrate de altera a tabela Athlete e o método de associação para o ORM.

2020-09-11 00:48 UTC, merged