Recursos Iniciais - Módulo 5
IBAD-Ibirama/ibad pull request #6
Opened 2020-08-09 21:11 UTC by JefiPNZ

Desenvolvidos recursos referentes a primeira sprint do módulo 5:

- Relatório de Competições
- Desempenho do Atleta
- Relatório Financeiro.

2020-09-16 07:07 UTC, GustavoSantosCS requested changes, later dismissed
Creio que a padronização do Laravel padroniza a nomenclatura dos Modelos em singular! O mesmo vale para o Controller.

Há uma duplicidade de classe modelo Athlete e Athletes! Deve-se remover a classe não utilizada.

2020-09-16 07:07 UTC, GustavoSantosCS commented on database/seeds/AthleteSeeder.php
> +        DB::table('athletes')->insert([
Ao usar o DB e não informar as colunas created_at e updated_at estes assumiram valor nulo!
Use o método estático da classe ::create para os campos ser preenchidos pela Laravel

2020-09-16 07:07 UTC, GustavoSantosCS commented on database/seeds/CategoriesSeeder.php
> +        DB::table('categories')->insert([
Ao usar o DB e não informar as colunas created_at e updated_at estes assumiram valor nulo!
Use o método estático da classe ::create para os campos ser preenchidos pela Laravel

2020-09-16 07:07 UTC, GustavoSantosCS commented on database/seeds/ModalitiesSeeder.php
> +        DB::table('modalities')->insert([
Ao usar o DB e não informar as colunas created_at e updated_at estes assumiram valor nulo!
Use o método estático da classe ::create para os campos ser preenchidos pela Laravel

2020-09-16 07:07 UTC, GustavoSantosCS commented on app/Http/Controllers/CompetitionController.php
> +    }
Somente um comentário!
Não entendi a necessidade do if na linha 37!  esse método é chamado apenas na rota ele sempre vai receber um id.
As linha 39 e 40 também não parece agregar muito já que essa variáveis não tem nenhum impacto na view ou no método de update

2020-09-16 07:07 UTC, GustavoSantosCS commented on app/Http/Controllers/CompetitionController.php
> +
o método dd é útil para desenvolvimento! em produção não é indicado o uso, um retorno mais amigável para o usuário é indicado

2020-09-16 07:07 UTC, GustavoSantosCS commented on app/Http/Controllers/CompetitionController.php
> +        $id;
Variável não utilizada!

2020-09-16 07:07 UTC, GustavoSantosCS commented on database/migrations/2020_10_04_012527_create_competitions_table.php
> +            $table->string('descricao');
Coluna descricao da tabela competitions em português! o padrão adota é Inglês!

2020-09-16 07:07 UTC, GustavoSantosCS commented on database/migrations/2020_10_04_012656_create_competition_participation_table.php
> +            $table->timestamps();
Apenas um comentário!
Creio que seja padrão do Laravel que as chaves estrangeiras devem ter o nome no singular.
Mas isso não possui muita importância.

2020-09-16 07:07 UTC, GustavoSantosCS commented on database/migrations/2020_10_08_220551_create_finances_table.php
> +            $table->increments('id');
Apenas um comentário.
O Laravel tem o método $table->id(); que realiza o mesmo trabalho que essa linha!

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/atletas/cadastroRegistroCompeticao.blade.php
> +                                    <label for="competition">Competicao</label>
Verificar ortografia de Competição

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/atletas/cadastroRegistroCompeticao.blade.php
> +                                </div>
no placeholder Nível esta sem acento

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/atletas/cadastroRegistroCompeticao.blade.php
> +            debugger
debugger deve ser removido!

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/atletas/cadastroRegistroCompeticao.blade.php
> +    function controllerCompetition() {
Por ser apenas o cadastro de evento onchange caso haja apenas **uma** competição cadastrada, os dados não serão sentados! Isso porque a única será o valor inicial o ComboBox.

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/competicoes/alterar.blade.php
> +                            <label for="competition_level">Nivel da Competicao</label>
Verificar a falta de acentos!

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/atletas/cadastroRegistroCompeticao.blade.php
> +                                    <input type="text" class="form-control" id="date" name="date" placeholder="data da competição" readonly>
Todos os placeholder dessa view tem a primeira palavra em maiúsculo com exceção desse campo.

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/competicoes/cadastrar.blade.php
> +                        @method('POST')
Apenas um comentário!
Esse método não é necessário.

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/competicoes/alterar.blade.php
> +                        @method('POST')
O padrão é utilizar o método PUT para atualizar os dados! A adoção do padrão remove a necessidade de acrescentar na URL o '/atualizar'.

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/competicoes/cadastrar.blade.php
> +                            <label for="competition_level">Nivel da Competicao</label>
Verificar a falta de acentos!

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/competicoes/index.blade.php
> +                                        <form style="display: inline" action="/competicao/remove/{{$competition->id}}" method="delete">
Apenas um comentário!
Não há necessidade  de adicionar "/remove" na url ao remover. O método DELETE vai diferenciar essa rota das outras.

2020-09-16 07:07 UTC, GustavoSantosCS commented on resources/views/competicoes/relatorio.blade.php
> +            <textarea class="form-control" id="informacoesEquipe" name="informacoes" placeholder="Informações da equipe no Relatório">A etapa foi promovida por (promovedor), e a equipe de (cidade) re
Apenas um comentário!
Os textos do placeholder não possuem padrão!  Há alguns com todas as palavras com a primeira letra maiúscula, outros com somente a primeira letra da primeira palavra maiúscula. Aconselho adotar um padrão.

2020-09-16 07:07 UTC, GustavoSantosCS commented on routes/web.php
> +Route::post('competicao/atualizar'  , 'CompetitionController@update');
Método de atualização de recurso deve ser PUT

2020-09-16 07:07 UTC, GustavoSantosCS commented on routes/web.php
> +Route::get('competicao/remove/{id}' , 'CompetitionController@destroy');
Método de remoção de recurso deve ser DELETE

2020-09-29 01:50 UTC, GustavoSantosCS submitted a review, later dismissed

2020-09-29 02:00 UTC, lucasfusinato requested changes

2020-09-29 02:00 UTC, lucasfusinato commented on er dump-autoload
> +    docs: Create README and add LICENSE
Creio que este arquivo pode ser removido.

2020-09-29 02:11 UTC, lucasfusinato approved these changes

2020-09-29 02:16 UTC, GustavoSantosCS approved these changes

2020-09-29 02:18 UTC, merged